apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fmkorea-hotdeal-monitor-data
  labels:
    app: fmkorea-hotdeal-monitor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
