apiVersion: v1
kind: Secret
metadata:
  name: fmkorea-hotdeal-monitor-secret
type: Opaque
stringData:
  slack-webhook-url: "REPLACE_WITH_SLACK_WEBHOOK_URL"
  discord-webhook-url: "REPLACE_WITH_DISCORD_WEBHOOK_URL"
  telegram-bot-token: "REPLACE_WITH_TELEGRAM_BOT_TOKEN"
  telegram-chat-id: "REPLACE_WITH_TELEGRAM_CHAT_ID"
